tnt:
  power: 10           #how many TNTs
  cooldown: 20        #in ticks; 20 ticks = 1 s

chance:
  same: true          #boolean
  same_chance: 0.05   #0 to 1
  colors:             #white, orange, magenta, light_blue, yellow, lime, pink, gray, light_gray, cyan, purple, blue, brown, green, red, black
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.05